### ISSUE TITLE
Make the pod simulator's image updateable

### ISSUE THREAD

**Issue by MrSupiri** [MrSupiri/rancher-logging-pipeline-plumber#40]
currently, pod simulator's image and tag is hardcoded to `supiri/pod-simulator:latest` and can't update to use `supiri/pod-simulator:dev` if needed

**Comment by paynejacob** [comment]
These values should also be configurable in the helm chart and able to be passed to the operator as arguments.

**Comment by paynejacob** [comment]
verified on `v0.1.0-alpha`
