### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by paynejacob** [MrSupiri/rancher-logging-pipeline-plumber#42]
I observed a flow test marked as passed when the simulation pod failed to start.  The aggregator shows log messages from the target pod.  We need to ensure we only consume logs from our simulation pod.  I suggest we add a label to our simulation pods and start all our matches with a match for that label.  We  can ignore that statement when we are testing but it will ensure we only get logs from the simulation pod.  This will prevent false positives when we are testing specific log messages.

**Comment by paynejacob** [comment]
discussed in standup, this is likely because the match statements use or logic.  We may want to switch to a filter.

**Comment by paynejacob** [comment]
version: `0.1.0-rc5`

I am seeing operator logs in the aggregator indices

```
{"stream":"stdout","logtag":"F","message":"foo","kubernetes":{"pod_name":"cfadc92b-ceec-4793-8a76-e59eba480f2b-simulation","namespace_name":"sut","pod_id":"0cc0b1f5-2403-4271-871e-6f1402c99447","labels":{"app.kubernetes.io/created-by":"logging-plumber","app.kubernetes.io/managed-by":"logging-pipeline-plumber","app.kubernetes.io/name":"pod-simulation","bar":"true","baz":"true","foo":"true","loggingplumber.isala.me/flowtest":"match-fail-first","loggingplumber.isala.me/flowtest-uuid":"cfadc92b-ceec-4793-8a76-e59eba480f2b"},"host":"k3d-lpp-server-0","container_name":"ubuntu","docker_id":"8cca3b43f06dc06a300d8c177444dd96c108c8dd382de3a82c801a84b333e9e8","container_image":"ghcr.io/mrsupiri/rancher-logging-pipeline-plumber/pod-simulator:v0.1.0-a5"}}
```

**Comment by MrSupiri** [comment]
This message was sent from the simulation pod, right? `"message":"foo"`, `"pod_name":"cfadc92b-ceec-4793-8a76-e59eba480f2b-simulation"`

**Comment by paynejacob** [comment]
That message was seen in the log aggregator index.  As a result.

**Comment by paynejacob** [comment]
verified on `v0.1.0-rc2`
